### ISSUE TITLE
[RFC] Add repo luci-abandoned

### ISSUE THREAD

**Issue by feckert** [openwrt/luci#1177]
I have seen that the packages `luci-app-ushare` and `luci-app-radvd` are declared as broken, because the packages `ushare` and `radvd` are not in the package feed Repository anymore. I always get a warning
`WARNING: No feed for package 'ushare' found, maybe it's already part of the standard packages?` and
`WARNING: No feed for package 'radvd' found, maybe it's already part of the standard packages?`  

To get rid of this warning and to see what packages need a new maintainer or should be get fixed, I think it es a good idea to add a `luci-abandoned` Repository the as for the packages feed.

Any comments?

**Comment by hnyman** [comment]
I don't think that it is really necessary, as I think that you will only get that warning when you have specifically selected to see also the BROKEN packages. And then you are already more or less in a special maintenance mode.  

Additional repos will only increase maintenance burden.

So, I am not very warm to the idea.

**Comment by feckert** [comment]
@hnyman i am not sure if i made a mistake!
I have dis selected the option `BROCKEN=n` but i still get this warning. I think if a package is marked as `@BROCKEN` it should also not get installed and the warning should not be displayed.

If i want to the see which packages need maintenance the i could enable the `BROCKEN=y` flag and see the warning. The i can pick up a package and fix it. But during normal development it should not be displayed because everything should look fine.

**Comment by hnyman** [comment]
Yep, looks like it is not related to BROKEN, after all. I remembered wrong.

But I tested and could not get those errors to show up except with the initial creation of the symlinks when first "installing" the feed packages to the build system. There are similar errors regarding asterisk etc. (and also for some core system packages, I think).

To me those look like harmless one-time errors that user sees once when he creates the build system for the first time. As the LuCI packages are marked broken, no normal user will find them in menuconfig, so the missing dependencies should not cause any harm. 

Like I said, having a separate luci-abandoned does not sound necessary to me.

Much easier would be to just delete those LuCI packages wholly. It is now three years since the repo revamp with "oldpackages", and so far nobody has imported either radvd or ushare to the new packages repo...

Or the packages can be left in broken status like they are now.

**Comment by feckert** [comment]
@hnyman You convinced me that a separate repository is not necessary. (What about the `packages-abandoned` should this not delete as well?)

I am using the software `buildbot` for continuous integration. The system will build always from scratch if i do a commit like the lede build-system.
The system will check all warning an error messages. So i always get the warning if i recreate the build env. I think the flag `BROCKEN` is a good tag for packages which need maintenance.
Is it possible to not install the package which are tag the the `BROCKEN` flag?

If someone want to install `BROCKEN` package the the flag should be set in the .config file.

Another possibility could be to add an additional flag to the feed install script to not install `BROCKEN` packages

**Comment by hnyman** [comment]
> What about the packages-abandoned should this not delete as well?

Good question. So far there are only 27 commits into that repo...

There are also several packages in the packages main repo that have been practically abandoned by the original maintainer. Bit-rot is slowly creeping in. But as there may be users for the packages, moving them into abandoned repo seems harsh.

But the realism is that there is no real "package police" that would be moving the semi-abandoned packages en masse.

**Comment by feckert** [comment]
I think we can close this no further comments
