### ISSUE TITLE
add a feature to the minidlna luci interface

### ISSUE THREAD

**Issue by davygrvy** [openwrt/luci#1758]
This now sets force_sort_criteria option.  It would need translations that I haven't done.  source file is luci/applications/luci-app-minidlna/luasrc/model/cbi/minidlna.lua

[luci-app-minidlna.diff.txt](https://github.com/openwrt/luci/files/1936229/luci-app-minidlna.diff.txt)

**Comment by dibdot** [comment]
Please open a regular PR for that.

**Comment by davygrvy** [comment]
If you have a GIT dev setup, please do so, thank you

**Comment by geekycow** [comment]
minidlna 1.3.3 on OpenWRT 24.10.4 still lacks the 'force_sort_criteria' option.

Might it be possible for the patch above to be implemented?  

It would mean a lot to me and a number of others with popular clients (such as Samsung TVs) that insist on sorting music tracks alphabetically by title rather than respecting track order.

Either way, thanks for reading, and thanks for your work on this.
