### ISSUE TITLE
Network device scan returns "Bad gateway" if scan takes more than 60 seconds

### ISSUE THREAD

**Issue by mroek** [openwrt/luci#234]
The function "Network device scan" is useful, but if the scan takes more than 60 seconds, no results are given, instead just the response "Bad Gateway", and the text "The process did not produce any response".

I've tried looking into the source, but I can't find a timeout value of 60 seconds, so I am wondering why this happens. And also, the link to start the scans has a warning saying that it could "take a few minutes", so the intention was probably not to cut it off with an error after 1 minute.

This function would be a lot more useful if it could run until completion, instead of timing out after 1 minute.

**Comment by dfc-d** [comment]
The network device scan stuff really needs to be rewritten.  It's been broken due to the default script timeout in uhttpd for at least two stable releases.  An ajax-based as-the-results-come-in / keep-alive is needed rather than trying to do a full scan within 60 seconds (which is typically too short a time period).

**Comment by cshoredaniel** [comment]
This is a bug that is unlikely to go anyware unless someone from the community decides to work on it, in the meantime package has been marked BROKEN.
