### ISSUE TITLE
LuCi Rosy Enhancement Request

### ISSUE THREAD

**Issue by davidc502** [openwrt/luci#2635]
Enhancement Request for LuCi Rosy

Replace word LEDE with OpenWrt for the Splash Screen and General pages.

**Comment by dibdot** [comment]
@rosysong

**Comment by rosysong** [comment]
@davidc502  Could you please show us where is the word "LEDE" in LuCI Rosy theme ?

**Comment by hnyman** [comment]
> Replace word LEDE with OpenWrt for the Splash Screen and General pages.

Likely the same old thing again: It is not branding, but hostname.
The router's config has LEDE as the host name in /etc/config/system (from the old default config). That gets shown on the upper left corner.

LuCI source code has no "LEDE" word in the rosy theme.

I have named my own router as "router1", so it says that instead of "OpenWrt":

![image](https://user-images.githubusercontent.com/7926856/54877370-3ebfed00-4e26-11e9-9e9c-ce073aac7508.png)

**Comment by dibdot** [comment]
no more feedback from @davidc502  - seems to be fixed.

**Comment by davidc502** [comment]
Sorry.. I haven't kept good track of this non-issue.. confirmed -- Not a branding issue, but where LuCi pulls the name from which is the system file.  I changed the option hostname lede to OpenWrt, and after a reboot LuCi displays OpenWrt.  

thanks for the help.
