### ISSUE TITLE
Add Estonian translation

### ISSUE THREAD

**Issue by laurivosandi** [openwrt/luci#296]
Hello,

could you please add template .po file for Estonian translation? Currently there is no Estonian translation available at http://luci.subsignal.org/pootle to even get started.

**Comment by chris5560** [comment]
@laurivosandi late answer but better the never ;-)
Since LuCI code moved to Github, Pootle is no longer available.
Inside the various branches you find the .pot templates to generate the corresponding .po files i.e. using poedit or any other editor you prefer.
When contributing keep in mind, that old OpenWrt/LuCI releases are not auto recompiled and distributed to the download servers.
Christian
