### ISSUE TITLE
LuCI Wifi not updated to reflect new options

### ISSUE THREAD

**Issue by gwlim** [openwrt/luci#3035]
> daemon.notice netifd: radio0 (2539): Usage:    iw [options] dev <devname> set channel <channel> [NOHT|HT20|HT40+|HT40-|5MHz|10MHz|80MHz]
daemon.notice netifd: radio0 (2539): Options:
daemon.notice netifd: radio0 (2539):   --debug         enable netlink debugging
user.notice mac80211: Failed command: iw dev wlan0 set channel 40 HT40

I think iw as been updated to use new HT options but LuCI still save the options using the old HT options
I have to manually edit /etc/config/wireless and change the HT40 to HT40+ or HT40-

**Comment by jow-** [comment]
This is a bug of https://github.com/openwrt/openwrt/blob/master/package/kernel/mac80211/files/lib/netifd/wireless/mac80211.sh. `HT40` is a legal UCI value which is supposed to get translated to either `HT40+` or `HT40-`. I believe the code at https://github.com/openwrt/openwrt/blob/master/package/kernel/mac80211/files/lib/netifd/wireless/mac80211.sh#L514 is simply superfluous since the channel setting already happens in https://github.com/openwrt/openwrt/blob/master/package/kernel/mac80211/files/lib/netifd/wireless/mac80211.sh#L623
