### ISSUE TITLE
luci-app-shadowsocks-libev: servers page broken in latest luci

### ISSUE THREAD

**Issue by ysc3839** [openwrt/luci#3316]
@jow- @yousong 
The "Remote Servers" page is broken in new version of luci, showing "TypeError Cannot read property 'id' of undefined".
I found it's because `UIDropdown.__init__` is not called, which is caused by `super` function.
https://github.com/openwrt/luci/blob/1df1421221a2e22334668e6c5524fc359f21d32d/modules/luci-base/htdocs/luci-static/resources/luci.js#L267-L291
I don't know why `superContext` is not a local veriable. Because of this, `superContext` remains `LuCI.View` when `UIDropdown.__init__` is called. So `__init__` is not found and not called.

**Comment by jow-** [comment]
@ysc3839 - `superContext` is global because a function invoked by `super()` might call `super()` itself too. In order to prevent an infinite recursion, that inner `super()` function call must not start traversing the prototype chain from `this` again, but start with the scope where the outer `super()` function call left off - which is stored in `superContext`.

I found the logic flaw however; it happened when a `super()` function looking for one symbol, lead to the calling of a method also invoking `super()` but for another symbol. In this particular case an outer `super('renderFooter')` was calling an inner `super('__init__')` which messed up the context saved in `superContext`. To solve this issue, I turned `superContext` into dictionary where the prototype scope pointers are stored keyed by symbol we're currently looking up.

This appears to solve the problem but I'd appreciate if you can give it a spin as well.

This is the patch: https://gist.github.com/jow-/1c6b195f98e6db8c08b35388351f095b

**Comment by yousong** [comment]
Confirmed working.  No errors anymore and "Import Links" works.

By the way, I think luci-app-shadowsocks-libev now does not depend on luci-compat.  I have run-tested with luci-compat uninstalled and saw no error.  But I do not yet familiarize myself with the current code enough to be sure.

**Comment by ysc3839** [comment]
Tested and seems no issue.

**Comment by yousong** [comment]
Reopen as the patch is not yet in the repo.

@jow- , it seems the patch cannot handle the case where the same symbol were called by another object of different class type, e.g.  typeAObj.super('__init__') invokes typeBObj.super('__init__')

**Comment by jow-** [comment]
@yousong - that is correct. Any idea how to handle it? Unfortunately one cannot use objects pointers as key in JS so we need to find a way to form a unique identity for the symbol/class combination we're looking up.

**Comment by yousong** [comment]
> @yousong - that is correct. Any idea how to handle it? Unfortunately one cannot use objects pointers as key in JS so we need to find a way to form a unique identity for the symbol/class combination we're looking up.

How about making `superContext` collection of stacks keyed by symbol name, pushing and popping on entry/exit of `super()`.

It's ephemeral, specific to the call stack initiated by the first obj.super() call.

`superContext` is stored with obj.

**Comment by jow-** [comment]
@yousong - thanks for the suggestion. I opted for a different approach in the end which was easier for me to wrap my head around.

**Comment by yousong** [comment]
@jow- Likely it's not enough and a stack-like structure is required.

Let's consider the following case.  The 2nd and 3rd `super('render')` calls are at the same level.  Context will be cleared on return from 2nd call, causing the 3rd call starting from scratch invoking method of child class.

```
obj.super('render')
  obj.super('render')
  obj.super('render')
```
