### ISSUE TITLE
luci-proto-qmi is not displaying link informations - @feckert : I think this is not a pullrequest.

### ISSUE THREAD

**Issue by bgiboudeau** [openwrt/luci#3365]
I reopen my issue following feckert recommendation.
------------------------------------------
I think this is not a pullrequest.
@bgiboudeau please open an issue.

_Originally posted by @feckert in https://github.com/openwrt/luci/pull/3364#issuecomment-559111352_
-----------------------------------------

I opened first an issue for it and been asked to open a pullrequest and asked again to open an issue. So I execute it one last time and let deal with the situation if you think it's an intresting topic to tackle. To be clear I will not reopen anything but if you guys need extract of commands on a router I can help you guys.

-----------------------------------------
Initial message below.

It would be great if we can have in the status section some details about the link status.
Something a bit like the Wifi status section, it's very helpfull to see quickly where do we stand with the radio interface.

Some informations from the command : uqmi -d "modem" --get-signal-info

Link type : LTE, 3G, GPRS, ...
rssi / rsrq / rsrp & snr.

Some informations from the command : uqmi -d "modem" --get-serving-system
-registration
plmn_mcc
plmn_mnc
plmn_description
roaming
Thanks a lot
bgiboudeau

below the output of the two commands.
First command: /sbin/uqmi -d /dev/cdc-wdm0 --get-signal-info

{
"type": "lte",
"rssi": -67,
"rsrq": -10,
"rsrp": -90,
"snr": 250
}

Second command : uqmi -d /dev/cdc-wdm0 --get-serving-system

{
"registration": "registered",
"plmn_mcc": 208,
"plmn_mnc": 15,
"plmn_description": "Fy▒\u000c",
"roaming": false
}

So

**Comment by feckert** [comment]
I want to make that clear again.
**Issue:**
An issue can be a bug or a feature-request.
It's for developers and users to know what doesn't fit or what's need to be done.
An issue is only for tracking bugs / feature-requests.

**Pullrequest**
A pullrequest is a request to add new source code to the repository.
The discussion in a pullrequest refers to the source code that whats to be submitted.

**Conclution**
I hope I was able to clarify that.
In your use case you have to open an issue, because you want a feature.
When someone thinks this is useful he/she will implement this.

**Advice**
Please prepare for this before you are angry.
