### ISSUE TITLE
Broken repositories in package/feeds/luci/luci-proto-modemmanager/Makefile

### ISSUE THREAD

**Issue by dram80** [openwrt/luci#3507]
Hi,
I have issues with compiling of OpenWRT 19.07 from source. I get multiple _dependency missing_ or _recursive dependency detected_ error messages. Steps to reproduce fault is fairly easy:
* switch to 19.07 branch
* make distclean
* git pull
* ./scripts/feeds update -a
* ./scripts/feeds install -a
* make menuconfig and choose any target
* make defconfig and then following faults appear:

```
WARNING: Makefile 'package/feeds/luci/luci-proto-modemmanager/Makefile' has a dependency on 'modemmanager', which does not exist
tmp/.config-package.in:136570:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:136570:	symbol PACKAGE_vpn-policy-routing depends on PACKAGE_vpnbypass
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:136590:	symbol PACKAGE_vpnbypass depends on PACKAGE_vpn-policy-routing
#
# configuration written to .config
# 
```
No such issue was in 18.06.

**Comment by jow-** [comment]
The `luci-proto-modemmanager` package has been dropped. Neither `vpnbypass` nor `vpn-policy-routing` are part of this repository however so I'll close this here.

@stangri - I guess the recursive dependency is due to the `CONFLICTS` tag which lets the packages reference each other. Since `CONFLICTS` results in a negative kconfig dependency expression, you'll see the circular dependency. Only one of both package must conflict with the other.
