### ISSUE TITLE
Modal windows in openwrt2020 theme

### ISSUE THREAD

**Issue by dibdot** [openwrt/luci#3803]
@jow Just a quick one: is this a theme issue or is this an adblock issue (see screenshots)? In the older themes it looks OK, so I ask ...
![modal02](https://user-images.githubusercontent.com/8061346/78036104-3750ef00-736a-11ea-8196-2458bf2830b1.png)
![modal_01_2020](https://user-images.githubusercontent.com/8061346/78036116-3ae47600-736a-11ea-9b48-4d8f48729c7d.png)

**Comment by jow-** [comment]
This happens because the modal dialog in OpenWrt2020 is wider than the old themes. If you resize your browser window to become a little narrower you should see the elements snapping in place.

To make the layout more rigid, I suggest removing the `float: left;` directives and adding `style="display:flex; flex-direction:column"` to the parent `<div class="left">` instead.

**Comment by dibdot** [comment]
Indeed, you're right - thank you!
