### ISSUE TITLE
[luci-app-adblock] typeerror

### ISSUE THREAD

**Issue by blackTay** [openwrt/luci#3894]
After a fresh installation of adblock and luci-app-adblock on v19.02,  the "overview" section of services>adblock shows the error

> TypeError
> result[0].trim is not a function

and is loading infinitely long. Probably some javascript problem?

**Comment by superjamie** [comment]
For anyone else hitting this and landing here from search results, it appears to be fixed with an update, probably to the web interface Luci.

Use the System, Software web interface to update packages, or SSH into your router and update everything possible with `opkg update && opkg upgrade $(opkg list-upgradable | awk '{ print $1 }')`
