### ISSUE TITLE
luci-app-sqm: can't change settings

### ISSUE THREAD

**Issue by resadent** [openwrt/luci#3957]
Hi. I have openwrt from 19th april, I have seen no changes related to this since then so I figured Id post this.

I can't change settings in sqm via luci interface, ie. I can't click in save/apply button, save or reset button. This didn't happen at first but now I can't fix it no matter what I try, so I'm changing the settings via cli. Notice the buttons are not like in the second image where I'm able to click on them. I have tried changing the theme but no luck.
![image](https://user-images.githubusercontent.com/34896462/80098384-13e62200-856d-11ea-9705-98b7739ac435.png)
![image](https://user-images.githubusercontent.com/34896462/80098492-4728b100-856d-11ea-9779-747465582381.png)

**Comment by hnyman** [comment]
It should have been fixed in master on April 20th.

https://git.openwrt.org/?p=project/luci.git;a=commitdiff;h=74da73b012a7ac271d683f11d98de170215ae661;hp=760763a7b5da42860c6c2d63478859bb02fa9104#patch25

Remove and reinstall sqm.

Note that there has been buildbot trouble, so the updated package might not yet be there.

**Comment by resadent** [comment]
I confirm its fine with latest build compiled a few moments ago.
