### ISSUE TITLE
luci-app-mwan3: deadlock after browsing LuCI for some time

### ISSUE THREAD

**Issue by m01** [openwrt/luci#4228]
I'm not entirely sure how to reproduce this, but it happens regularly to me with version 2.8.7+ of `mwan3` (I didn't notice this issue with v. 2.8.4). The Overview page no longer loads, and I get lots of these in the output of `ps aflx`:

```
4     0 12337     1  20   0   6224  4656 ep_pol S    ?          0:03 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
..
0     0 27387 12337  20   0   2916  2008 do_wai S    ?          0:00  \_ /usr/bin/lua /www/cgi-bin/luci
0     0 27388 27387  20   0   1308  1040 do_wai S    ?          0:00  |   \_ /bin/sh /etc/rc.common /etc/init.d/mwan3 enabled
0     0 27392 27388  20   0   1192   544 locks_ S    ?          0:00  |       \_ flock 1000
0     0  1788 12337  20   0   2916  2012 do_wai S    ?          0:00  \_ /usr/bin/lua /www/cgi-bin/luci
0     0  1813  1788  20   0   1308  1032 do_wai S    ?          0:00  |   \_ /bin/sh /etc/rc.common /etc/init.d/mwan3 enabled
0     0  1826  1813  20   0   1192   548 locks_ S    ?          0:00  |       \_ flock 1000
0     0  1954 12337  20   0   2916  2012 do_wai S    ?          0:00  \_ /usr/bin/lua /www/cgi-bin/luci
0     0  1955  1954  20   0   1308  1040 do_wai S    ?          0:00      \_ /bin/sh /etc/rc.common /etc/init.d/mwan3 enabled
0     0  1959  1955  20   0   1192   484 locks_ S    ?          0:00          \_ flock 1000
```

Every time I go to the overview page it adds another one. I can't get the overview page to load anymore, until I manually clean up and/or stop `mwan3`.

It looks to me like there's a deadlock. I wonder if there's any way to make at least the read-only actions not require a lock (this problem might need to be solved in the packages repo rather than here)...

**Comment by jow-** [comment]
This problem is unrelated to LuCI and might not even be related to mwan3 at all. The lock descriptor 1000 is used by `/etc/rc.common` to ensure that certain common init script actions do not run concurrently. If a faulty init script wrongly inherits the open lock file descriptor 1000 to the daemon process it launches, the lock is held indefinitely and init scripts start piling up.

A similar problem has been workarounded in OpenWrt master recently, see https://github.com/openwrt/openwrt/commit/a03d6d2fab13c478a0f6cfc3082bec141f2adcf1

I am closing this ticket because it is unrelated to LuCI, but if you provide me the current list of your init scripts (`ls -l /etc/init.d/`) I might be able to help you track down the offending one.
