### ISSUE TITLE
Inconsistent list handling in uci config file

### ISSUE THREAD

**Issue by Mirodin** [openwrt/luci#4827]
In OpenWrt 19.07 starting from standard config line:

`firewall.wan.network='wan wan6'`

When creating an interface via Luci and assigning it to the ‘wan’ firewall zone the following gets created (old style list):

`firewall.wan.network='wan wan6 vpn'`

Running

`uci add_list firewall.wan.network='vpn'`

results in an invalid config:

`firewall.wan.network='wan wan6' 'vpn'`

I am not sure if this is a Luci or uci bug but it is reproducible in 19.07, see my forum thread about this: https://forum.openwrt.org/t/inconsistent-list-handling-in-uci-and-luci/89260

I posted the same issue over at the OpenWrt issue tracker: https://bugs.openwrt.org/index.php?do=details&task_id=3637

**Comment by hnyman** [comment]
Reference to discussion at:
https://forum.openwrt.org/t/inconsistent-list-handling-in-uci-and-luci/89260

I tested with LuCI, and LuCI adds the interfaces to zones with the old "option" style, instead of using the "list" style:
```
config zone
        option name 'test'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'REJECT'
        option network 'test2 test3'
```

And once that has happened, then uci continues to further mangle styles if you use cli to add new interfaces to the zone.

Like this:
```
root@router1:~# tail -n 4 /etc/config/firewall
config zone 'test'
        option name 'test'
        option network 'wan henet'

root@router1:~# uci add_list firewall.test.network="ttt"
root@router1:~# uci commit firewall

root@router1:~# tail -n 5 /etc/config/firewall
config zone 'test'
        option name 'test'
        list network 'wan henet'
        list network 'ttt'
```

Note that the "option" was converted to "list" without breaking the two items to separate lines but the third item was added as a separate item.

I tested with 21.02 (=master).  

The default firewall zone network item config style has been "list" since 2013 by this commit
https://github.com/openwrt/openwrt/commit/3bb397c99700b4645445cc0cc0955078a7b35d02
