### ISSUE TITLE
wireless band select bug in N mode

### ISSUE THREAD

**Issue by CWZ7605** [openwrt/luci#4964]
With the dual-band wireless module, the 2.4G band cannot be selected in N mode
![图片](https://user-images.githubusercontent.com/4016785/113589754-59a7d780-9664-11eb-88f0-0169734e897a.png)
![图片](https://user-images.githubusercontent.com/4016785/113589948-970c6500-9664-11eb-941e-b458796a2cee.png)

**Comment by dragetd** [comment]
The 'Operating frequency' is for compatibility within this band, not for switching between 2,4ghz/5ghz. Every available device should have its own 'radioX' entry, one for 2,4ghz, one for 5ghz and more, if you have multiple devices.

You have radio0 and radio1 and you can configure wireless interfaces in any more on one of these.

It would be helpful if you could rephrase and explain what the issue is. What you expect to happen and what happens instead.
Also, please add which device you are using and which version of OpenWRT, as not every device is equally well supported.

**Comment by jow-** [comment]
Not a bug.
