### ISSUE TITLE
/usr/lib/lua/luci/dispatcher.lua:427: /etc/config/luci seems to be currupt, unable to find section "main"

### ISSUE THREAD

**Issue by BUG-reporter** [openwrt/luci#5026]
After upgrading from 19.07.7 to 21.02.0-rc1 (with previous configuration saving) Luci is not working with the following message while trying to enter it:
![image](https://user-images.githubusercontent.com/2866407/116796157-17e34300-aae3-11eb-963a-64564c352ca8.png)

**Comment by dibdot** [comment]
Most probably not a LuCI bug, check your config (see https://github.com/openwrt/luci/issues/4758 for reference).

**Comment by BUG-reporter** [comment]
Config is default immediately after upgrading.

**Comment by dibdot** [comment]
Did you check/correct the config as mentioned in the referenced ticket - esp. the ubus path?

**Comment by alan636** [comment]
I am sure that "/usr/lib/lua/luci/dispatcher.lua:427: /etc/config/luci seems to be corrupt, unable to find section 'main'" is a bug and continues happening in OpenWrt 21 version. Because after I used the stress test tool named [Jmeter](https://github.com/apache/jmeter) with 2,000 HTTP connection threads of an internet website then the Openwrt main page lose the response and showed that text in the browser when I refresh. 

![image](https://user-images.githubusercontent.com/41531958/227111750-0a693a75-85be-45de-bdcd-4073912befc8.png)
![image](https://user-images.githubusercontent.com/41531958/227111969-3cadede7-227e-4429-a9f7-2f0f76bcee15.png)

**Comment by alan636** [comment]
> I am sure that "/usr/lib/lua/luci/dispatcher.lua:427: /etc/config/luci seems to be corrupt, unable to find section 'main'" is a bug and continues happening in OpenWrt 21 version. Because after I used the stress test tool named [Jmeter](https://github.com/apache/jmeter) with 2,000 HTTP connection threads of an internet website then the Openwrt main page lose the response and showed that text in the browser when I refresh.
> 
> ![image](https://user-images.githubusercontent.com/41531958/227111750-0a693a75-85be-45de-bdcd-4073912befc8.png) ![image](https://user-images.githubusercontent.com/41531958/227111969-3cadede7-227e-4429-a9f7-2f0f76bcee15.png)

It is not ruled out that the low performance of the router is the cause, but even the low performance of the router should ensure the normal operation of the management interface webpage, or restore the normal operation of the management interface webpage after the pressure drops.

**Comment by jow-** [comment]
This error also could mean that the `rpcd` service crashed and did not recover, check your routers `logread` for details.
