### ISSUE TITLE
RPCError: luci.wireguard/getWgInstances failed with error -32000: Object not found

### ISSUE THREAD

**Issue by peterwillcn** [openwrt/luci#5521]
```
RPCError
RPC call to luci.wireguard/getWgInstances failed with error -32000: Object not found
  at ClassConstructor.handleCallReply (https://172.20.0.1/luci-static/resources/rpc.js?v=git-21.226.86205-376af36:11:3)
```

**Comment by jow-** [comment]
The wireguard application received various rpc related fixes since commit 376af36:

8950c9f66c luci-app-wireguard: replace luci-app-wireguard
d98935c45b luci-app-wireguard: merge app and proto rpcd
8530232f51 luci-proto-wireguard: client qr code generation
03d615f62c luci-proto-wireguard: add more options to qr code
f062ce76c3 luci-proto-wireguard: update i18n
9d560c46cc luci-app-wireguard: fix dependency
88d7cc1261 luci-proto-wireguard: fix luci.wireguard rpcd dependency
193abe7221 luci-app-wireguard: fix allowed_ip parsing
01ecb1ac8a luci-proto-wireguard: fix markup not valid for XHTML
44445a8097 luci-proto-wireguard: fix potential shell injection vulnerabilities
eff38ed724 luci-app-wireguard: fix i18n of "ago"

I assume this issue is fixed in master already.
