### ISSUE TITLE
luci-app-mwan3: can't add interfaces

### ISSUE THREAD

**Issue by paladin4fan** [openwrt/luci#5760]
## Steps to reproduce:

1. go to: Network → Multiwan→interfaces tab
2. delete all default interfaces here, then create a new interface, setting the tracking IP and enable it
3. Save & Apply
4. go to: interfaces setting tab again

## Actual behavior:

1. nothing shows here, the interfaces keeps empty
2. no interface information in /etc/config/mwan3

## Expected behavior:

```
Correctly show the interface message in both luci and config file
```

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r19364-6af46796fa'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r19364-6af46796fa'
DISTRIB_TAINTS=''
```

**Comment by feckert** [comment]
I can reproduce the error.


However, if I use `save&apply` from the uci change overview then it works.

![Screenshot 2022-06-21 at 16-20-37 st-dev-07 - Interface - LuCI](https://user-images.githubusercontent.com/553091/174822942-42967cf8-443d-4eb1-bed7-5f96191d3e3e.png)

Strange?

**Comment by openwrtdiy** [comment]
Also found a new issue: When setting the assigned policy: wan_wanb, the network failover did not take effect. After uploading and installing MWAN3_2.8.16, the policy will take effect.

**Comment by feckert** [comment]
Only the openwrt-21.02 branch works as expected because this is still using the lua facility.

The master and openwrt-22.03 branch does not work as expected!

I have changed the luci-app-wan3 so that it now uses javascript in this branches.
But I am sure that everything already worked after javascript migration.
Somewhere a regression slipt in.


Interesting is, that I can't edit the section after creating it. I am getting a empty modal.
![Screenshot 2022-07-12 at 11-29-56 st-dev-07 - Mitglied - LuCI](https://user-images.githubusercontent.com/553091/178458872-ba465f24-aa6c-4762-828d-12594689bbc2.png)
But if I go into another luci-app-* and back again, then I can edit it.

Very funny behaviour.  @jow- can you help us there?
I have already looked at the history but have not seen any suspicious commit.
I have to mention that when I go to the modal **Unsaved changes** and click on `Save & Apply`, the configuration gets applied and will be saved!

![Screenshot 2022-07-12 at 11-41-44 st-dev-07 - Mitglied - LuCI](https://user-images.githubusercontent.com/553091/178461531-6532516a-fa11-46af-81c3-ed656ad1ca4a.png)

**Comment by paladin4fan** [comment]
> That muss be a generic problem. Could you verify if this is als

I've compiled from 22.03.0-RC5 and tried submit through uci change overview
And it works.

**Comment by paladin4fan** [comment]
> I can reproduce the error.
> 
> However, if I use `save&apply` from the uci change overview then it works.
> 
> ![Screenshot 2022-06-21 at 16-20-37 st-dev-07 - Interface - LuCI](https://user-images.githubusercontent.com/553091/174822942-42967cf8-443d-4eb1-bed7-5f96191d3e3e.png)
> 
> Strange?
> 
> @paladin4fan Could you verify if this is the same on your system?
> 
> That muss be a generic problem. Could you verify if this is also not working for application that uses the same Luci template [gridsection](https://github.com/openwrt/luci/blob/master/applications/luci-app-mwan3/htdocs/luci-static/resources/view/mwan3/network/interface.js#L26)

BTW in menber tabs it got a new issue
I can't add member continuously. If I add a new member follow the former member without submit from uci changes overview, the hinder member will cover the former one.

**Comment by feckert** [comment]
I use the Luci pattern here. So nothing special. This should also be the case with other apps. Can you confirm this?

**Comment by jow-** [comment]
It is indeed a generic LuCI issue. Just tracked down the problem but still thinking about a proper solution.

**Comment by 1715173329** [comment]
wonder if 21.02 branch also needs this fix... form.js looks pretty old there
