### ISSUE TITLE
X5000R 5GHz radio showing incorrect Wifi MAC address

### ISSUE THREAD

**Issue by liukuohao** [openwrt/luci#5768]
I bought 2 X5000R routers, and all units are showing the same MAC address in the 5GHz radio in Luci Wireless Overview.

![5GHz Radio not correctly shown- refer to No 2](https://user-images.githubusercontent.com/94607852/163724555-7b16d257-5d20-4dd8-a825-8d8aa9d6052c.jpg)

![TOTOLI~2](https://user-images.githubusercontent.com/94607852/163724505-7ffc3a3a-6dc4-4ebc-8af0-292cffa9b580.JPG)

**Comment by liukuohao** [comment]
Basically ALL the versions of 21.02.X & also the latest branch 22.03.0

Another issue is 21.02.3 firmware still does not work well with 5GHz radio. 
It will cause to have TypeError red message pop out when you are saving
settings. In order to solve this entirely, only the new branch 22.03.0 works

**Comment by jow-** [comment]
This is caused by a too old libiwinfo in OpenWrt base which does not understand the new `option path ...+1` syntax used to identify the 5GHz radio phy. This has all sorts of weird side effects, like not being to identify the available operation modes, frequencies and so on.

I backported libiwinfo updates into the openwrt-21.02 branch now, the autobuilders will pick those up eventually and push new package versions to the binary repos. To fix the issue, you can then upgrade `libiwinfo20210430` via opkg.

OpenWrt 21.02.4 will contain the updated package directly then.

**Comment by liukuohao** [comment]
**THANK YOU** for fixing the problem.
