### ISSUE TITLE
LUCI_LANG_ur： Warning notices

### ISSUE THREAD

**Issue by zxlhhyccc** [openwrt/luci#5886]
![image](https://user-images.githubusercontent.com/45259624/179334327-1f5d3d8b-b28d-4e52-a5f4-513f6c0bcdbd.png)
![image](https://user-images.githubusercontent.com/45259624/179334339-c0f27197-22a0-471a-b982-e75555dc904f.png)

**Comment by ptpt52** [comment]
same issue here:
```
tmp/.config-package.in:59941:warning: leading whitespace ignored
```

**Comment by feckert** [comment]
So I don't get this warning!
I have seen that there are more and more translations that are not listed in the luci.mk.
Maybe one of you @ptpt52 @zxlhhyccc can sync this and add the missing information to luci.mk.
So far, these translations are not built because they do not have an entry in luci.mk.

**Comment by hnyman** [comment]
> So far, these translations are not built because they do not have an entry in luci.mk.

Actually, they are being built.
E.g. the ur / urdu has zero strings translated, but the base.po has been created in weblate.
No translation files for other apps have been started.

The base.po download exists quite normally, e.g.
```
luci-i18n-base-ur_git-22.200.34529-5d7af48_all.ipk | 1.1 KB | Thu Jul 21 12:11:2022
https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/luci/luci-i18n-base-ur_git-22.200.34529-5d7af48_all.ipk
```

The warning is cosmetic and due to the missing language name, which leads into leading space from the parsing in
https://github.com/openwrt/luci/blob/master/luci.mk#L288

**Comment by ptpt52** [comment]
how to fix it?
