### ISSUE TITLE
luci: mesh_fwding must be written to mesh11sd if the config exists instead of wireless

### ISSUE THREAD

**Issue by Sophronia-AK** [openwrt/luci#6495]
In the wireless interface configuration section, the mesh forwarding config is available. 
This configuration must be mapped to mesh11sd uci config if the mesh11sd uci is available oand only be written to wireless if mesh11sd uci does not exist.

**Comment by bluewavenet** [comment]
@Sophronia-AK 

> This configuration must be mapped to mesh11sd uci config 

No, that is not necessary because mesh11sd overrides whatever mesh parameters that may be set in the wireless config.

If the mesh11sd daemon is running in its default management mode, then if you want to set mesh forwarding to "0" then do it in the mesh11sd config. Note this will be dynamic and take effect immediately without having to restart the wireless. This means you can turn it off and on at will, keeping everything up (this goes for all supported mesh parameters). Don't do a `uci commit mesh11sd` unless you want the change to survive a reboot.

**Comment by Sophronia-AK** [comment]
@bluewavenet  Thank you it works !
