### ISSUE TITLE
[Bug] luci-base: Reset button is not working in Network Wireless Section

### ISSUE THREAD

**Issue by sahilsuman933** [openwrt/luci#6514]
## Steps to reproduce:

Go to the Network → Wireless Section then click on the reset button. 

## Actual behavior:
The reset button is not functioning properly. Even after pressing it, all the preset configurations remain unchanged.

## Expected behavior:

The reset button should clear all changes made by the user and restore the preset configuration. In this case, it should remove all user settings, such as the example settings mentioned here.
![image](https://github.com/openwrt/luci/assets/34382211/6f74d96a-884b-42b4-b8e9-dfaa6e8679d0)

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.5'
DISTRIB_REVISION='r20134-5f15225c1e'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 22.03.5 r20134-5f15225c1e'
DISTRIB_TAINTS=''
```

Note: If you believe this is a bug, I can submit a pull request to help resolve the issue.

**Comment by jow-** [comment]
> The reset button should clear all changes made by the user and restore the preset configuration

No, the reset button is an artifact of the generic CBI map handling and is supposed to simply re-render the form to revert all input fields to their initial state. It is not meant to revert to factory configuration.

It probably makes little sense on the wireless configuration page since all actual config is happening in modal forms, so it's probably best to simply remove it on this page.
