### ISSUE TITLE
„Weblate“ locked (again), errors. (CONFLICT (content): Merge conflict in applications/luci-app-firewall/po/lt/firewall.po)

### ISSUE THREAD

**Issue by dziugas1959** [openwrt/luci#6878]
As I already mentioned in „Help translate the web interface via weblate“
![300978349-3cbabc3b-4ea2-40b4-be21-3043b845f663](https://github.com/openwrt/luci/assets/53124670/ff98ac95-4fd9-4241-887d-0231b991e8fa)
![300978471-e435d0e3-a86e-4a21-936b-9f0c15420704](https://github.com/openwrt/luci/assets/53124670/e2103f1f-1e3c-4f78-a199-5241c812cf0c)

**Comment by dziugas1959** [comment]
P.S all languages are affected.

**Comment by hnyman** [comment]
Yeah, I am pretty sure that it is related to commits made directly to language files by @systemcrash a few hours ago.
I haven't yet figure out which of the recent commits it was.
(Firewall, network and luci-base are somewhat intertwined)

Weblate is annoyingly picky about direct git changes to files that are included in its open PRs.
As best practice to avoid conflicts, I have learned to first merge the open Weblate PRs, and only then edit / merge other language file changes.

**Comment by hnyman** [comment]
Fixed with b6e968b

This was a pretty peculiar failure. 
No clear direct git commits touching firewall or statistics components, except weblate's own PR commits. 

Looks like a race/concurrency problem, where somebody have just translated one or more strings and weblate has launched an periodic commit process and it simultaneously receives a trigger of upstream repository change (direct git commit to LuCI repo).

The first failed/conflicting strings are translated here:
![image](https://github.com/openwrt/luci/assets/7926856/b55928c4-978d-43ae-a1c8-77f983ecbef9)


When a few hours late @systemcrash makes edit via weblate interface, it then suddenly notices a conflict. Based on the edits needed, the conflict was related to weblate changes made by @dziugas1959 a few hours earlier via weblate itself.

![image](https://github.com/openwrt/luci/assets/7926856/f2b5b9a4-03e9-4a82-8b72-ed48971a60dd)

So, weblate was in conflict with changes made via itself. :-(
First time that we have seen that, I think.

**Comment by systemcrash** [comment]
😅
