### ISSUE TITLE
LuCI doesn't apply changes for odhcpd service e.g. dhcp.lan.dns_service

### ISSUE THREAD

**Issue by robehub** [openwrt/luci#7050]
## Steps to reproduce:

1. go to: Network → Interfaces → LAN → DHCP server tab → IPv6 settings tab
2. uncheck 'Local IPv6 DNS server'
3. Save & Apply
4. reconnect/renew your computer to obtain new DHCP configuration

## Actual behavior:
DNS Servers IPv6 address still available on computer ip configuration

## Expected behavior:
DNS Servers IPv6 shouln't be visible in local computer ipconfig

## Additional Information:
if odhcpd service was restarted manually, all works as expected and IPv6 DNS Server is not provided by DHCP

**Comment by systemcrash** [comment]
Technically this isn't a luci problem. But you could try the following:

In your dhcp config:
```
config odhcpd 'odhcpd'
	...
	option loglevel '7'
```

Run a wireshark capture of icmpv6 and see what RA that are coming out of the router have in terms of Options. For DNS it's 25.

Restart odhcpd. 

Observe the odhcpd syslog entries to ensure a restart happens.. 

Toggle the problem setting (apply) Toggle it again (apply).

I just tested your settings change and it worked fine for me. If you can find some combination where it doesn't work, write again here. But it seems the problem is at your workstation.
